#!/bin/bash

echo "[🚀] Initiating Day 9: The Evidence PDF Factory..."

# 1. Ensure directories exist
mkdir -p src/services
mkdir -p outputs

# 2. Build the PDF Generation Service
cat << 'CODE' > src/services/pdfService.ts
import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';

// Define the shape of the data we will inject into the PDF
export interface EvidenceData {
    disputeId: string;
    chargeId: string;
    amount: number;
    reason: string;
    date: string;
    organizationName: string;
}

export const generateCompellingEvidence = async (data: EvidenceData): Promise<string> => {
    let browser;
    try {
        // Build the raw HTML template. In production, this can be expanded 
        // to include IP addresses, AVS checks, and Whop tracking logs.
        const htmlContent = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <style>
                    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; padding: 40px; }
                    .header { border-bottom: 2px solid #0056b3; padding-bottom: 10px; margin-bottom: 20px; }
                    .title { font-size: 24px; font-weight: bold; color: #0056b3; }
                    .subtitle { font-size: 14px; color: #666; }
                    .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                    .data-table th, .data-table td { padding: 12px; border: 1px solid #ddd; text-align: left; }
                    .data-table th { background-color: #f8f9fa; font-weight: bold; width: 30%; }
                    .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="title">Compelling Evidence Report</div>
                    <div class="subtitle">Generated by Novoriq Revenue OS</div>
                </div>
                
                <p>To whom it may concern at the issuing bank,</p>
                <p>This document serves as compelling evidence to contest the dispute filed for the transaction detailed below. The customer actively authorized this charge for services rendered by <strong>${data.organizationName}</strong>.</p>
                
                <table class="data-table">
                    <tr><th>Dispute ID</th><td>${data.disputeId}</td></tr>
                    <tr><th>Charge ID</th><td>${data.chargeId}</td></tr>
                    <tr><th>Dispute Reason</th><td>${data.reason.toUpperCase()}</td></tr>
                    <tr><th>Transaction Amount</th><td>$${(data.amount / 100).toFixed(2)} USD</td></tr>
                    <tr><th>Transaction Date</th><td>${data.date}</td></tr>
                    <tr><th>Service Status</th><td>Delivered & Accessed via Whop</td></tr>
                </table>

                <div class="footer">
                    Document generated automatically via cryptographic audit trail. <br>
                    Novoriq OS Timestamp: ${new Date().toISOString()}
                </div>
            </body>
            </html>
        `;

        // Launch headless browser. 
        // --no-sandbox is critical for Linux environments to prevent execution crashes.
        browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });

        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

        // Define output path
        const fileName = `evidence_${data.disputeId}.pdf`;
        const outputPath = path.join(__dirname, '../../outputs', fileName);

        // Render PDF
        await page.pdf({
            path: outputPath,
            format: 'A4',
            printBackground: true,
            margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
        });

        return outputPath;

    } catch (error) {
        console.error("[CRITICAL] PDF Generation Failed:", error);
        throw new Error("Failed to generate evidence PDF.");
    } finally {
        // STRICT MEMORY MANAGEMENT: Ensure browser is always closed, even if an error occurs.
        if (browser) {
            await browser.close();
        }
    }
};
CODE

# 3. Build the Automated Simulation Script
cat << 'TEST' > src/test_day9.ts
import { PrismaClient } from '@prisma/client';
import { generateCompellingEvidence } from './services/pdfService';
import fs from 'fs';

const prisma = new PrismaClient();

async function runAudit() {
    console.log("\n[🔒] Running Evidence PDF Factory Simulation...\n");

    try {
        // 1. Fetch the dispute we generated in Day 8
        const dispute = await prisma.dispute.findFirst({
            include: {
                payment: true,
                organization: true
            }
        });

        if (!dispute) {
            throw new Error("No dispute found in database. Run Day 8 simulation first.");
        }

        console.log(`-> Extracting data for Dispute: ${dispute.stripeId}`);
        
        // 2. Format data for the PDF engine
        const evidenceData = {
            disputeId: dispute.stripeId,
            chargeId: dispute.payment.stripeChargeId,
            amount: dispute.payment.amount,
            reason: dispute.reason,
            date: dispute.payment.createdAt.toISOString().split('T')[0],
            organizationName: dispute.organization.name
        };

        console.log("-> Launching Headless Browser (Puppeteer)...");
        const pdfPath = await generateCompellingEvidence(evidenceData);

        // 3. Verify the file exists on the hard drive
        if (fs.existsSync(pdfPath)) {
            console.log(`\n[✅] SUCCESS: Compelling Evidence PDF successfully generated.`);
            console.log(`     File Location: ${pdfPath}`);
        } else {
            console.log("\n[❌] FAILURE: PDF file not found at expected path.");
        }

    } catch (err) {
        console.error("\n[❌] Audit Failed:", err);
    } finally {
        await prisma.$disconnect();
        process.exit(0);
    }
}

setTimeout(runAudit, 1000);
TEST

echo "[✅] PDF Factory Service Built. Executing simulation..."
npx ts-node src/test_day9.ts
