import puppeteer from 'puppeteer';
import path from 'path';
import fs from 'fs';

export interface EvidenceData {
    disputeId: string;
    chargeId: string;
    amount: number;
    reason: string;
    date: string;
    organizationName: string;
    customerName: string;
    customerEmail: string;
    billingAddress?: string;
    cvcCheck?: string;
    avsCheck?: string;
    customerIp?: string;
    deviceFingerprint?: string;
    location?: string;
}

export const generateCompellingEvidence = async (data: EvidenceData): Promise<string> => {
    let browser;
    try {
        // Build the HTML using a clean, formal, legal-style layout
        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #2d3748; line-height: 1.5; }
                    .header { border-bottom: 3px solid #1a202c; padding-bottom: 10px; margin-bottom: 30px; }
                    .header h1 { margin: 0; color: #1a202c; font-size: 24px; letter-spacing: 1px; }
                    .header p { margin: 5px 0 0 0; color: #4a5568; font-size: 14px; }
                    .section { margin-bottom: 25px; }
                    .section-title { background-color: #f7fafc; padding: 10px 15px; border-left: 4px solid #2b6cb0; font-size: 14px; font-weight: bold; text-transform: uppercase; margin-bottom: 15px; }
                    table { width: 100%; border-collapse: collapse; font-size: 13px; }
                    td { padding: 10px 5px; border-bottom: 1px solid #edf2f7; }
                    .label { font-weight: bold; color: #4a5568; width: 40%; }
                    .value { color: #1a202c; }
                    .pass { color: #2f855a; font-weight: bold; }
                    .alert { color: #c53030; font-weight: bold; }
                    .footer-text { font-size: 11px; color: #718096; margin-top: 40px; text-align: justify; font-style: italic; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>FORMAL DISPUTE REBUTTAL & EVIDENCE DOSSIER</h1>
                    <p>Generated by Novoriq Recovery Engine on behalf of <strong>${data.organizationName}</strong></p>
                </div>

                <div class="section">
                    <div class="section-title">1. Transaction & Dispute Summary</div>
                    <table>
                        <tr><td class="label">Dispute ID:</td><td class="value">${data.disputeId}</td></tr>
                        <tr><td class="label">Stripe Charge ID:</td><td class="value">${data.chargeId}</td></tr>
                        <tr><td class="label">Disputed Amount:</td><td class="value alert">$${(data.amount / 100).toFixed(2)} USD</td></tr>
                        <tr><td class="label">Dispute Reason:</td><td class="value" style="text-transform: capitalize;">${data.reason}</td></tr>
                        <tr><td class="label">Transaction Date:</td><td class="value">${data.date}</td></tr>
                    </table>
                </div>

                <div class="section">
                    <div class="section-title">2. Customer Identity & Authorization</div>
                    <table>
                        <tr><td class="label">Customer Name:</td><td class="value">${data.customerName}</td></tr>
                        <tr><td class="label">Email Address:</td><td class="value">${data.customerEmail}</td></tr>
                        <tr><td class="label">Billing Address:</td><td class="value">${data.billingAddress || 'Not Provided'}</td></tr>
                        <tr><td class="label">CVC Verification:</td><td class="value pass">${data.cvcCheck || 'Match'}</td></tr>
                        <tr><td class="label">AVS Verification:</td><td class="value pass">${data.avsCheck || 'Match'}</td></tr>
                    </table>
                </div>

                <div class="section">
                    <div class="section-title">3. Digital Footprint & Delivery Proof</div>
                    <table>
                        <tr><td class="label">Purchasing IP Address:</td><td class="value">${data.customerIp || 'N/A'}</td></tr>
                        <tr><td class="label">Geographic Location:</td><td class="value">${data.location || 'N/A'}</td></tr>
                        <tr><td class="label">Device Fingerprint:</td><td class="value">${data.deviceFingerprint || 'N/A'}</td></tr>
                    </table>
                </div>

                <div class="footer-text">
                    <strong>Declaration:</strong> The digital goods or services associated with this transaction were actively accessed and consumed via the account credentials matching the verified email address above. The CVC and Address Verification (AVS) systems passed security protocols at the time of purchase, proving explicit cardholder authorization. We respectfully request this chargeback be overturned in favor of the merchant.
                </div>
            </body>
            </html>
        `;

        // Safely ensure the output directory exists
        const outputDir = path.join(__dirname, '../../outputs');
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const fileName = `Novoriq_Evidence_${data.disputeId}.pdf`;
        const outputPath = path.join(outputDir, fileName);

        browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
        const page = await browser.newPage();
        
        // Load the HTML
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
        
        // Generate PDF (printBackground ensures the CSS colors/borders render)
        await page.pdf({ 
            path: outputPath, 
            format: 'A4',
            printBackground: true, 
            margin: { top: '20px', bottom: '20px' }
        });

        console.log(`[📄] Compelling Evidence Generated: ${fileName}`);
        return outputPath;

    } catch (error) {
        console.error(`[❌] PDF Generation Failed for ${data.disputeId}:`, error);
        throw error;
    } finally {
        if (browser) await browser.close();
    }
};